### ISSUE TITLE
Some buttons are very dark, and look like it is disabled

### ISSUE THREAD

**Issue by kjellskogsrud** [amantinband/amiko-dark#4]
The install button in the Nuget Package manager looks like it is disabled(but it's not).
Took me a minute to realize that it was actually possible to click. maybe make that a bit brighter?
![image](https://user-images.githubusercontent.com/5667385/202652930-462b4f7f-c107-4ddf-8d6c-67efe81c8543.png)

**Comment by K33pQu13t** [comment]
@amantinband I've tried to fix that, just simply set the color for control buttons like scrollbars color (which is from the right on first screen). On each screen, upper variant is the old one, bottom is my fix. Now i think it looks more active than disabled one :)

![изображение](https://github.com/amantinband/amiko-dark/assets/64601261/5852a723-44ab-48a6-823f-7d27198ea398)

![изображение](https://github.com/amantinband/amiko-dark/assets/64601261/59d69f33-8c0e-4e6e-99ec-6ffd8ef96104)

here is the PR if you agree with that: https://github.com/amantinband/amiko-dark/pull/9

**Comment by K33pQu13t** [comment]
Yeah, that looks like designed in new 1.4 version. Thanks!
